# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CWCG\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_dow = QtWidgets.QToolButton(self.widget)
        self.btn_dow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_dow.setObjectName("btn_dow")
        self.horizontalLayout.addWidget(self.btn_dow)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gb_general_info = QtWidgets.QGroupBox(self.widget)
        self.gb_general_info.setObjectName("gb_general_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_general_info)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.gb_general_info)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.gb_general_info)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_pay_load = QtWidgets.QWidget()
        self.tab_pay_load.setObjectName("tab_pay_load")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_pay_load)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.tab_pay_load)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tab_pay_load, "")
        self.tab_trim_load = QtWidgets.QWidget()
        self.tab_trim_load.setObjectName("tab_trim_load")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_trim_load)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.tab_trim_load)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tab_trim_load, "")
        self.tab_fuel = QtWidgets.QWidget()
        self.tab_fuel.setObjectName("tab_fuel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_fuel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.tab_fuel)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6.addWidget(self.widget_5)
        self.tabWidget.addTab(self.tab_fuel, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_file = QtWidgets.QMenu(self.menuBar)
        self.menu_file.setObjectName("menu_file")
        self.menu_view = QtWidgets.QMenu(self.menuBar)
        self.menu_view.setObjectName("menu_view")
        self.menu_envelop = QtWidgets.QMenu(self.menu_view)
        self.menu_envelop.setObjectName("menu_envelop")
        self.menu_tool = QtWidgets.QMenu(self.menuBar)
        self.menu_tool.setObjectName("menu_tool")
        MainWindow.setMenuBar(self.menuBar)
        self.action_save_case = QtWidgets.QAction(MainWindow)
        self.action_save_case.setObjectName("action_save_case")
        self.action_load_case = QtWidgets.QAction(MainWindow)
        self.action_load_case.setObjectName("action_load_case")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_print_report = QtWidgets.QAction(MainWindow)
        self.action_print_report.setObjectName("action_print_report")
        self.action_print_table = QtWidgets.QAction(MainWindow)
        self.action_print_table.setObjectName("action_print_table")
        self.action_zfw_envelop = QtWidgets.QAction(MainWindow)
        self.action_zfw_envelop.setObjectName("action_zfw_envelop")
        self.action_take_off_limit = QtWidgets.QAction(MainWindow)
        self.action_take_off_limit.setObjectName("action_take_off_limit")
        self.action_in_flight_limit = QtWidgets.QAction(MainWindow)
        self.action_in_flight_limit.setObjectName("action_in_flight_limit")
        self.action_landing_limit = QtWidgets.QAction(MainWindow)
        self.action_landing_limit.setObjectName("action_landing_limit")
        self.action_fuel_vector = QtWidgets.QAction(MainWindow)
        self.action_fuel_vector.setObjectName("action_fuel_vector")
        self.action_show_grid = QtWidgets.QAction(MainWindow)
        self.action_show_grid.setObjectName("action_show_grid")
        self.action_dow = QtWidgets.QAction(MainWindow)
        self.action_dow.setObjectName("action_dow")
        self.action_trim_sheet = QtWidgets.QAction(MainWindow)
        self.action_trim_sheet.setObjectName("action_trim_sheet")
        self.menu_file.addAction(self.action_save_case)
        self.menu_file.addAction(self.action_load_case)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_print_report)
        self.menu_file.addAction(self.action_print_table)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_envelop.addAction(self.action_zfw_envelop)
        self.menu_envelop.addAction(self.action_take_off_limit)
        self.menu_envelop.addAction(self.action_in_flight_limit)
        self.menu_envelop.addAction(self.action_landing_limit)
        self.menu_envelop.addAction(self.action_fuel_vector)
        self.menu_view.addAction(self.menu_envelop.menuAction())
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_show_grid)
        self.menu_tool.addAction(self.action_dow)
        self.menu_tool.addAction(self.action_trim_sheet)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_view.menuAction())
        self.menuBar.addAction(self.menu_tool.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dow.setText(_translate("MainWindow", "..."))
        self.gb_general_info.setTitle(_translate("MainWindow", "基本信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pay_load), _translate("MainWindow", "使用项目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trim_load), _translate("MainWindow", "配载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fuel), _translate("MainWindow", "燃油"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_view.setTitle(_translate("MainWindow", "视图"))
        self.menu_envelop.setTitle(_translate("MainWindow", "重量重心包线"))
        self.menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.action_save_case.setText(_translate("MainWindow", "保存算例"))
        self.action_load_case.setText(_translate("MainWindow", "导入算例"))
        self.action_quit.setText(_translate("MainWindow", "退出"))
        self.action_print_report.setText(_translate("MainWindow", "打印重量重心报告"))
        self.action_print_table.setText(_translate("MainWindow", "打印重量平衡表"))
        self.action_zfw_envelop.setText(_translate("MainWindow", "零油重量"))
        self.action_take_off_limit.setText(_translate("MainWindow", "起飞限制"))
        self.action_in_flight_limit.setText(_translate("MainWindow", "飞行限制"))
        self.action_landing_limit.setText(_translate("MainWindow", "着陆限制"))
        self.action_fuel_vector.setText(_translate("MainWindow", "燃油消耗曲线"))
        self.action_show_grid.setText(_translate("MainWindow", "网格线"))
        self.action_dow.setText(_translate("MainWindow", "空机重量"))
        self.action_trim_sheet.setText(_translate("MainWindow", "配平表"))
