# -*- coding: utf-8 -*-

from PyQt5.QtCore import QSize
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (QDialog, QGridLayout, QGroupBox, QLabel, QSpinBox, QAbstractSpinBox,
                             QDoubleSpinBox, QPushButton, QComboBox, QLineEdit, QDateEdit,
                             QHBoxLayout, QVBoxLayout, QTableView)


class WeighDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)

        font = QFont()
        font.setFamily('微软雅黑')
        self.setFont(font)
        self.resize(980, 890)
        self.gridLayout_5 = QGridLayout(self)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gb_result = QGroupBox(self)
        self.gb_result.setObjectName("gb_result")
        self.gridLayout = QGridLayout(self.gb_result)
        self.gridLayout.setObjectName("gridLayout")
        self.label_actual_cg = QLabel(self.gb_result)
        self.label_actual_cg.setObjectName("label_actual_cg")
        self.gridLayout.addWidget(self.label_actual_cg, 1, 0, 1, 1)
        self.spin_box_actual_weight = QSpinBox(self.gb_result)
        self.spin_box_actual_weight.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_actual_weight.setMinimum(0)
        self.spin_box_actual_weight.setMaximum(999999)
        self.spin_box_actual_weight.setObjectName("spin_box_actual_weight")
        self.gridLayout.addWidget(self.spin_box_actual_weight, 0, 1, 1, 1)
        self.label_empty_weight = QLabel(self.gb_result)
        self.label_empty_weight.setObjectName("label_empty_weight")
        self.gridLayout.addWidget(self.label_empty_weight, 2, 0, 1, 1)
        self.double_spin_box_actual_cg = QDoubleSpinBox(self.gb_result)
        self.double_spin_box_actual_cg.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.double_spin_box_actual_cg.setSingleStep(0.01)
        self.double_spin_box_actual_cg.setObjectName("double_spin_box_actual_cg")
        self.gridLayout.addWidget(self.double_spin_box_actual_cg, 1, 1, 1, 1)
        self.spin_box_empty_weight = QSpinBox(self.gb_result)
        self.spin_box_empty_weight.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_empty_weight.setMaximum(999999)
        self.spin_box_empty_weight.setObjectName("spin_box_empty_weight")
        self.gridLayout.addWidget(self.spin_box_empty_weight, 2, 1, 1, 1)
        self.label_empty_cg = QLabel(self.gb_result)
        self.label_empty_cg.setObjectName("label_empty_cg")
        self.gridLayout.addWidget(self.label_empty_cg, 3, 0, 1, 1)
        self.label_actual_weight = QLabel(self.gb_result)
        self.label_actual_weight.setObjectName("label_actual_weight")
        self.gridLayout.addWidget(self.label_actual_weight, 0, 0, 1, 1)
        self.double_spin_box_empty_cg = QDoubleSpinBox(self.gb_result)
        self.double_spin_box_empty_cg.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.double_spin_box_empty_cg.setObjectName("double_spin_box_empty_cg")
        self.gridLayout.addWidget(self.double_spin_box_empty_cg, 3, 1, 1, 1)
        self.btn_re_cal = QPushButton(self.gb_result)
        self.btn_re_cal.setMinimumSize(QSize(0, 22))
        self.btn_re_cal.setMaximumSize(QSize(16777215, 22))
        self.btn_re_cal.setObjectName("btn_re_cal")
        self.gridLayout.addWidget(self.btn_re_cal, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.gb_result, 0, 0, 1, 1)
        self.gb_general_info = QGroupBox(self)
        self.gb_general_info.setObjectName("gb_general_info")
        self.gridLayout_2 = QGridLayout(self.gb_general_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_aircraft_type = QLabel(self.gb_general_info)
        self.label_aircraft_type.setObjectName("label_aircraft_type")
        self.gridLayout_2.addWidget(self.label_aircraft_type, 0, 0, 1, 1)
        self.combo_box_aircraft_type = QComboBox(self.gb_general_info)
        self.combo_box_aircraft_type.setEditable(True)
        self.combo_box_aircraft_type.setObjectName("combo_box_aircraft_type")
        self.combo_box_aircraft_type.addItem("")
        self.combo_box_aircraft_type.addItem("")
        self.gridLayout_2.addWidget(self.combo_box_aircraft_type, 0, 1, 1, 1)
        self.label_aircraft_num = QLabel(self.gb_general_info)
        self.label_aircraft_num.setObjectName("label_aircraft_num")
        self.gridLayout_2.addWidget(self.label_aircraft_num, 1, 0, 1, 1)
        self.combo_box_aircraft_num = QComboBox(self.gb_general_info)
        self.combo_box_aircraft_num.setEditable(True)
        self.combo_box_aircraft_num.setObjectName("combo_box_aircraft_num")
        self.combo_box_aircraft_num.addItem("")
        self.combo_box_aircraft_num.addItem("")
        self.combo_box_aircraft_num.addItem("")
        self.gridLayout_2.addWidget(self.combo_box_aircraft_num, 1, 1, 1, 1)
        self.label_weigh_method = QLabel(self.gb_general_info)
        self.label_weigh_method.setObjectName("label_weigh_method")
        self.gridLayout_2.addWidget(self.label_weigh_method, 2, 0, 1, 1)
        self.combo_box_weigh_method = QComboBox(self.gb_general_info)
        self.combo_box_weigh_method.setEditable(True)
        self.combo_box_weigh_method.setObjectName("combo_box_weigh_method")
        self.combo_box_weigh_method.addItem("")
        self.gridLayout_2.addWidget(self.combo_box_weigh_method, 2, 1, 1, 1)
        self.label_weigh_loc = QLabel(self.gb_general_info)
        self.label_weigh_loc.setObjectName("label_weigh_loc")
        self.gridLayout_2.addWidget(self.label_weigh_loc, 3, 0, 1, 1)
        self.line_edit_loc = QLineEdit(self.gb_general_info)
        self.line_edit_loc.setObjectName("line_edit_loc")
        self.gridLayout_2.addWidget(self.line_edit_loc, 3, 1, 1, 1)
        self.label_weigh_date = QLabel(self.gb_general_info)
        self.label_weigh_date.setObjectName("label_weigh_date")
        self.gridLayout_2.addWidget(self.label_weigh_date, 4, 0, 1, 1)
        self.date_edit_weigh_date = QDateEdit(self.gb_general_info)
        self.date_edit_weigh_date.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.date_edit_weigh_date.setObjectName("date_edit_weigh_date")
        self.gridLayout_2.addWidget(self.date_edit_weigh_date, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.gb_general_info, 0, 1, 1, 1)
        self.group_box_weigh_first = QGroupBox(self)
        self.group_box_weigh_first.setObjectName("group_box_weigh_first")
        self.gridLayout_3 = QGridLayout(self.group_box_weigh_first)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_nose_right = QLabel(self.group_box_weigh_first)
        self.label_nose_right.setObjectName("label_nose_right")
        self.gridLayout_3.addWidget(self.label_nose_right, 0, 0, 1, 1)
        self.spin_box_nose_right = QSpinBox(self.group_box_weigh_first)
        self.spin_box_nose_right.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_nose_right.setObjectName("spin_box_nose_right")
        self.spin_box_nose_right.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_nose_right, 0, 1, 1, 1)
        self.label_nose_left = QLabel(self.group_box_weigh_first)
        self.label_nose_left.setObjectName("label_nose_left")
        self.gridLayout_3.addWidget(self.label_nose_left, 1, 0, 1, 1)
        self.spin_box_nose_left = QSpinBox(self.group_box_weigh_first)
        self.spin_box_nose_left.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_nose_left.setObjectName("spin_box_nose_left")
        self.spin_box_nose_left.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_nose_left, 1, 1, 1, 1)
        self.label_left_out = QLabel(self.group_box_weigh_first)
        self.label_left_out.setObjectName("label_left_out")
        self.gridLayout_3.addWidget(self.label_left_out, 2, 0, 1, 1)
        self.spin_box_left_out = QSpinBox(self.group_box_weigh_first)
        self.spin_box_left_out.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_left_out.setObjectName("spin_box_left_out")
        self.spin_box_left_out.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_left_out, 2, 1, 1, 1)
        self.label_left_in = QLabel(self.group_box_weigh_first)
        self.label_left_in.setObjectName("label_left_in")
        self.gridLayout_3.addWidget(self.label_left_in, 3, 0, 1, 1)
        self.spin_box_left_in = QSpinBox(self.group_box_weigh_first)
        self.spin_box_left_in.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_left_in.setObjectName("spin_box_left_in")
        self.spin_box_left_in.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_left_in, 3, 1, 1, 1)
        self.label_right_in = QLabel(self.group_box_weigh_first)
        self.label_right_in.setObjectName("label_right_in")
        self.gridLayout_3.addWidget(self.label_right_in, 4, 0, 1, 1)
        self.spin_box_right_in = QSpinBox(self.group_box_weigh_first)
        self.spin_box_right_in.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_right_in.setObjectName("spin_box_right_in")
        self.spin_box_right_in.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_right_in, 4, 1, 1, 1)
        self.label_right_out = QLabel(self.group_box_weigh_first)
        self.label_right_out.setObjectName("label_right_out")
        self.gridLayout_3.addWidget(self.label_right_out, 5, 0, 1, 1)
        self.spin_box_right_out = QSpinBox(self.group_box_weigh_first)
        self.spin_box_right_out.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_right_out.setObjectName("spin_box_right_out")
        self.spin_box_right_out.setMaximum(999999)
        self.gridLayout_3.addWidget(self.spin_box_right_out, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.group_box_weigh_first, 1, 0, 1, 1)
        self.group_box_weigh_second = QGroupBox(self)
        self.group_box_weigh_second.setObjectName("group_box_weigh_second")
        self.gridLayout_4 = QGridLayout(self.group_box_weigh_second)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_nose_right_2 = QLabel(self.group_box_weigh_second)
        self.label_nose_right_2.setObjectName("label_nose_right_2")
        self.gridLayout_4.addWidget(self.label_nose_right_2, 0, 0, 1, 1)
        self.spin_box_nose_right_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_nose_right_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_nose_right_2.setObjectName("spin_box_nose_right_2")
        self.spin_box_nose_right_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_nose_right_2, 0, 1, 1, 1)
        self.label_nose_left_2 = QLabel(self.group_box_weigh_second)
        self.label_nose_left_2.setObjectName("label_nose_left_2")
        self.gridLayout_4.addWidget(self.label_nose_left_2, 1, 0, 1, 1)
        self.spin_box_nose_left_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_nose_left_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_nose_left_2.setObjectName("spin_box_nose_left_2")
        self.spin_box_nose_left_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_nose_left_2, 1, 1, 1, 1)
        self.label_left_out_2 = QLabel(self.group_box_weigh_second)
        self.label_left_out_2.setObjectName("label_left_out_2")
        self.gridLayout_4.addWidget(self.label_left_out_2, 2, 0, 1, 1)
        self.spin_box_left_out_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_left_out_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_left_out_2.setObjectName("spin_box_left_out_2")
        self.spin_box_left_out_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_left_out_2, 2, 1, 1, 1)
        self.label_left_in_2 = QLabel(self.group_box_weigh_second)
        self.label_left_in_2.setObjectName("label_left_in_2")
        self.gridLayout_4.addWidget(self.label_left_in_2, 3, 0, 1, 1)
        self.spin_box_left_in_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_left_in_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_left_in_2.setObjectName("spin_box_left_in_2")
        self.spin_box_left_in_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_left_in_2, 3, 1, 1, 1)
        self.label_right_in_2 = QLabel(self.group_box_weigh_second)
        self.label_right_in_2.setObjectName("label_right_in_2")
        self.gridLayout_4.addWidget(self.label_right_in_2, 4, 0, 1, 1)
        self.spin_box_right_in_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_right_in_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_right_in_2.setObjectName("spin_box_right_in_2")
        self.spin_box_right_in_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_right_in_2, 4, 1, 1, 1)
        self.label_right_out_2 = QLabel(self.group_box_weigh_second)
        self.label_right_out_2.setObjectName("label_right_out_2")
        self.gridLayout_4.addWidget(self.label_right_out_2, 5, 0, 1, 1)
        self.spin_box_right_out_2 = QSpinBox(self.group_box_weigh_second)
        self.spin_box_right_out_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_right_out_2.setObjectName("spin_box_right_out_2")
        self.spin_box_right_out_2.setMaximum(999999)
        self.gridLayout_4.addWidget(self.spin_box_right_out_2, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.group_box_weigh_second, 1, 1, 1, 1)
        self.group_box_pillar = QGroupBox(self)
        self.group_box_pillar.setObjectName("group_box_pillar")
        self.horizontalLayout = QHBoxLayout(self.group_box_pillar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_ln = QLabel(self.group_box_pillar)
        self.label_ln.setObjectName("label_ln")
        self.horizontalLayout.addWidget(self.label_ln)
        self.spin_box_ln = QSpinBox(self.group_box_pillar)
        self.spin_box_ln.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_ln.setObjectName("spin_box_ln")
        self.spin_box_ln.setMaximum(9999)
        self.horizontalLayout.addWidget(self.spin_box_ln)
        self.label_lml = QLabel(self.group_box_pillar)
        self.label_lml.setObjectName("label_lml")
        self.horizontalLayout.addWidget(self.label_lml)
        self.spin_box_lml = QSpinBox(self.group_box_pillar)
        self.spin_box_lml.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_lml.setObjectName("spin_box_lml")
        self.spin_box_lml.setMaximum(9999)
        self.horizontalLayout.addWidget(self.spin_box_lml)
        self.label_lmr = QLabel(self.group_box_pillar)
        self.label_lmr.setObjectName("label_lmr")
        self.horizontalLayout.addWidget(self.label_lmr)
        self.spin_box_lmr = QSpinBox(self.group_box_pillar)
        self.spin_box_lmr.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_box_lmr.setObjectName("spin_box_lmr")
        self.spin_box_lmr.setMaximum(9999)
        self.horizontalLayout.addWidget(self.spin_box_lmr)
        self.gridLayout_5.addWidget(self.group_box_pillar, 2, 0, 1, 2)
        self.group_box_component_list = QGroupBox(self)
        self.group_box_component_list.setObjectName("group_box_component_list")
        self.horizontalLayout_2 = QHBoxLayout(self.group_box_component_list)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.group_box_surplus = QGroupBox(self.group_box_component_list)
        self.group_box_surplus.setObjectName("group_box_surplus")
        self.verticalLayout = QVBoxLayout(self.group_box_surplus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_view_surplus = QTableView(self.group_box_surplus)
        self.table_view_surplus.setObjectName("table_view_surplus")
        self.verticalLayout.addWidget(self.table_view_surplus)
        self.horizontalLayout_2.addWidget(self.group_box_surplus)
        self.group_box_lack = QGroupBox(self.group_box_component_list)
        self.group_box_lack.setObjectName("group_box_lack")
        self.verticalLayout_2 = QVBoxLayout(self.group_box_lack)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_view_lack = QTableView(self.group_box_lack)
        self.table_view_lack.setObjectName("table_view_lack")
        self.verticalLayout_2.addWidget(self.table_view_lack)
        self.horizontalLayout_2.addWidget(self.group_box_lack)
        self.gridLayout_5.addWidget(self.group_box_component_list, 3, 0, 1, 2)

        self.translate()

        self.btn_re_cal.clicked.connect(self.calculate_weight_cg)

    # 计算重量重心
    def calculate_weight_cg(self):
        pass

    def translate(self):
        self.setWindowTitle("空机数据")
        self.gb_result.setTitle("称重结果")
        self.label_actual_cg.setText("实测重心（%MAC）")
        self.label_empty_weight.setText("空机重量（kg）")
        self.label_empty_cg.setText("空机重心（%MAC）")
        self.label_actual_weight.setText("实测重量（kg）")
        self.btn_re_cal.setText("计算重量重心")
        self.gb_general_info.setTitle("基本信息")
        self.label_aircraft_type.setText("飞机型号")
        self.combo_box_aircraft_type.setItemText(0, "C919")
        self.combo_box_aircraft_type.setItemText(1, "ARJ21-700")
        self.label_aircraft_num.setText("架机号")
        self.combo_box_aircraft_num.setItemText(0, "10102")
        self.combo_box_aircraft_num.setItemText(1, "10105")
        self.combo_box_aircraft_num.setItemText(2, "10106")
        self.label_weigh_method.setText("称重方式")
        self.combo_box_weigh_method.setItemText(0, "地秤称重法")
        self.label_weigh_loc.setText("称重地点")
        self.label_weigh_date.setText("称重日期")
        self.group_box_weigh_first.setTitle("第一次称重(kg)")
        self.label_nose_right.setText("前起右侧-NR")
        self.label_nose_left.setText("前起左侧-NL")
        self.label_left_out.setText("左主起外侧-LO")
        self.label_left_in.setText("左主起内侧-LI")
        self.label_right_in.setText("右主起内侧-RI")
        self.label_right_out.setText("右主起外侧-RO")
        self.group_box_weigh_second.setTitle("第二次称重(kg)")
        self.label_nose_right_2.setText("前起右侧-NR")
        self.label_nose_left_2.setText("前起左侧-NL")
        self.label_left_out_2.setText("左主起外侧-LO")
        self.label_left_in_2.setText("左主起内侧-LI")
        self.label_right_in_2.setText("右主起内侧-RI")
        self.label_right_out_2.setText("右主起外侧-RO")
        self.group_box_pillar.setTitle("支柱行程")
        self.label_ln.setText("前起支柱行程（mm）")
        self.label_lml.setText("左主起支柱行程（mm）")
        self.label_lmr.setText("左主起支柱行程（mm）")
        self.group_box_component_list.setTitle("多/缺装件清单")
        self.group_box_surplus.setTitle("多装件")
        self.group_box_lack.setTitle("缺装件")
